### ISSUE TITLE
Add new weapons

### ISSUE THREAD

**Issue by Nimajjj** [Nimajjj/APAWCALYPSE#115]
22 l rifle: 1 bullet magazin, mid damage, high accuracy
357 magnum: 6 bullets magazin, high damage, mid accuracy

**Comment by Nimajjj** [comment]
pisto lazer
lance roquet
la daronne de anta

**Comment by Bahsiik** [comment]
zefoizjefoizjefozijefoizjefoizjefoizjefoizjef
